# Generated by Django 5.0.6 on 2025-04-08 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.cours')),
                ('userOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
            options={
                'unique_together': {('titre', 'userOwner', 'cours')},
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userCollab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.note')),
            ],
        ),
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.note')),
                ('userEditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
        ),
    ]
