# Generated by Django 5.1.7 on 2025-05-15 11:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_pdfnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNoteResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.IntegerField(default=1)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.note')),
                ('userEditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
            options={
                'unique_together': {('note', 'userEditeur', 'version')},
            },
        ),
    ]
