# Generated by Django 5.1.7 on 2025-05-15 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_quiznote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdenConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_interaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='EdenMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_assistant', models.BooleanField(default=False)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='landing.edenconversation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
