# Generated by Django 5.1.7 on 2025-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_edenconversation_edenmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiznote',
            name='contenu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
