# Generated by Django 5.1.7 on 2025-05-15 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20250515_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('titre', models.CharField(default='Audio sans titre', max_length=200)),
                ('duree', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.note')),
                ('userEditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='OcrNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=200)),
                ('texte_extrait', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.note')),
                ('userEditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='VideoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('titre', models.CharField(default='Vidéo sans titre', max_length=200)),
                ('duree', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.note')),
                ('userEditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customuser')),
            ],
        ),
    ]
