# Generated by Django 5.0.6 on 2025-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_quiznote_questions_audionote_ocrnote_videonote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiznote',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
