# Generated by Django 5.0.6 on 2025-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_quiznote_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiznote',
            name='questions',
            field=models.TextField(default='[]'),
        ),
    ]
