# Generated by Django 5.0.6 on 2025-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_quiznote_questions_audionote_ocrnote_videonote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiznote',
            name='questions',
            field=models.JSONField(default=dict),
        ),
    ]
