# Generated by Django 5.0.6 on 2025-05-22 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_quiznote_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url_api', models.URLField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_encrypted', models.BinaryField()),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='landing.aiprovider')),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_gratuit', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=False)),
                ('est_defaut', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='landing.aiprovider')),
            ],
            options={
                'ordering': ['provider', 'ordre', 'nom'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
